sudo: false

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

language: ruby

cache: bundler

matrix:
  include:
    - rvm: 2.3.1
      script:
        - bundle exec danger
    - rvm: 2.3.1
      env:
        - GRAPE_SWAGGER_VERSION=0.8.0
    - rvm: 2.3.1
      env:
        - GRAPE_SWAGGER_VERSION=0.9.0
    - rvm: 2.3.1
      env:
        - GRAPE_SWAGGER_VERSION=0.11.0
    - rvm: 2.3.1
      env:
        - GRAPE_SWAGGER_VERSION=0.20.2
    - rvm: 2.3.1
      env:
        - GRAPE_SWAGGER_VERSION=HEAD
    - rvm: 2.3.0
    - rvm: 2.2.5
    - rvm: 2.0.0
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby-head
  allow_failures:
    - env: GRAPE_SWAGGER_VERSION=HEAD
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2

