name: Tests
on:  
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ (matrix.grape-swagger.experimental) || (matrix.ruby.experimental) }}
    strategy:
      fail-fast: false
      matrix:
        grape-swagger:
          - { version: "0.8.0", experimental: false }
          - { version: "0.9.0", experimental: false }
          - { version: "0.11.0", experimental: false }
          - { version: "0.20.2", experimental: false }
          - { version: "0.33.0", experimental: false }
          - { version: "HEAD", experimental: true }
        ruby:
          - { version: "2.5.6", experimental: false }
          - { version: "ruby-head", experimental: true }
          - { version: "jruby-head", experimental: true }
    env:
      GRAPE_SWAGGER_VERSION: ${{ matrix.grape-swagger.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.version }}
          bundler-cache: true
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: "54.0"
      - uses: browser-actions/setup-geckodriver@latest
        with:
          geckodriver-version: "0.18.0"
      - uses: GabrielBB/xvfb-action@v1
        with:
          run: bundle exec rake spec
